import './grid';
import './slider';
import './cities';
import './popup';
import './order-form/order-form';
import './validations/validation'
import './validations/areas';
import './validations/forSubmit';
import '../css/styles.less';